### ISSUE TITLE
Preferred timezone is considered an email field

### ISSUE THREAD

**Issue by nickytonline** [Virtual-Coffee/hacktoberfest#23]
## Description

When I filled out the mentorship form, I was unable to submit because it said the preferred timezone was not a valid email address

## Expected Behaviour

I should be able to add a preferred timezone as a regular text field

**Comment by danieltott** [comment]
Thanks @nickytonline - JUST fixed this in 0c7fdfa12897d5bbfb873a51111fc8f61ef24a79 😁
